# Site Configuration
# AI Gov Consulting - Global site settings

site:
  title: "AI Gov Consulting"
  tagline: "Transforming Local Government Through AI Innovation"
  description: "Expert AI consulting for local governments. Led by CEO Keith Williams. We help municipalities modernize operations, enhance citizen services, and build smarter communities through strategic AI implementation."
  url: "https://aigovconsulting.com"
  author: "Keith Williams, CEO"
  language: "en"
  
  # Contact Information
  phone: "+1 (555) 555-1234"
  phone_raw: "+15555551234"
  email: "keith@aigovconsulting.com"
  whatsapp: "15555551234"
  
  # Location
  location:
    city: "United States"
    region: "Nationwide Service"
    coordinates:
      latitude: 39.8283
      longitude: -98.5795
  
  # Social Media (set real URLs or leave empty to hide)
  social:
    facebook: ""
    instagram: ""
    linkedin: "https://linkedin.com/in/keith-williams"
    twitter: ""
  
  # SEO Keywords
  keywords:
    - "AI consulting local government"
    - "government AI transformation"
    - "municipal AI solutions"
    - "smart city consulting"
    - "government technology consulting"
    - "AI for municipalities"
    - "citizen service AI"
    - "government operations AI"
    - "public sector AI consulting"

# Build Configuration
build:
  output_dir: "docs"
  static_dir: "static"
  template_dir: "templates"
  
# Feature Flags
features:
  show_blog: false
  show_testimonials: true
  show_whatsapp_float: true
  show_pricing: true
  enable_analytics: false
